# Generated by Django 4.2.9 on 2024-01-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoltStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="NutStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WasherStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Washer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50)),
                ("thickness_washer", models.FloatField()),
                ("width_washer", models.FloatField()),
                ("diameter", models.IntegerField()),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="distance_checker.washerstandard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case", models.CharField(max_length=50)),
                ("left_girder_angle", models.FloatField()),
                ("right_girder_angle", models.FloatField()),
                ("girder_height", models.IntegerField()),
                ("left_t_flange_girder", models.IntegerField()),
                ("right_t_flange_girder", models.IntegerField()),
                ("t_plate_connection", models.IntegerField()),
                (
                    "bolt_grade",
                    models.TextField(choices=[("8_8", "8.8"), ("10_9", "10.9")]),
                ),
                ("bolt_diameter", models.IntegerField()),
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("distance_left", models.IntegerField(null=True)),
                ("distance_right", models.IntegerField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50)),
                ("thickness_nut", models.FloatField()),
                ("width_nut", models.FloatField()),
                ("diameter", models.IntegerField()),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="distance_checker.nutstandard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Corner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case", models.CharField(max_length=50)),
                ("girder_angle", models.FloatField()),
                ("girder_height", models.IntegerField()),
                ("t_flange_girder", models.IntegerField()),
                ("column_width", models.IntegerField()),
                ("t_flange_column", models.IntegerField()),
                ("t_plate_connection", models.IntegerField()),
                (
                    "bolt_grade",
                    models.TextField(choices=[("8_8", "8.8"), ("10_9", "10.9")]),
                ),
                ("bolt_diameter", models.IntegerField()),
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("distance_top", models.IntegerField(null=True)),
                ("distance_bottom", models.IntegerField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bolt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50)),
                ("thickness_bolt_head", models.FloatField()),
                ("width_bolt_head", models.FloatField()),
                ("length", models.IntegerField()),
                ("diameter", models.IntegerField()),
                ("thread_length", models.FloatField()),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="distance_checker.boltstandard",
                    ),
                ),
            ],
        ),
    ]
