# Generated by Django 4.2.6 on 2023-10-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('distance_checker', '0005_rename_name_corner_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corner',
            name='case',
            field=models.CharField(default='Corner', max_length=50),
        ),
    ]
