# Generated by Django 4.2.6 on 2023-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('distance_checker', '0007_alter_corner_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corner',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='corner',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
