# Generated by Django 4.2.6 on 2023-10-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('distance_checker', '0008_alter_corner_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corner',
            name='bolt_diameter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='corner',
            name='bolt_grade',
            field=models.TextField(choices=[('8_8', '8.8'), ('10_9', '10.9')]),
        ),
        migrations.AlterField(
            model_name='corner',
            name='case',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='corner',
            name='column_width',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='corner',
            name='distance_bottom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corner',
            name='distance_top',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corner',
            name='girder_angle',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='corner',
            name='girder_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='corner',
            name='t_flange_column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='corner',
            name='t_flange_girder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='corner',
            name='t_plate_connection',
            field=models.IntegerField(),
        ),
    ]
