# Generated by Django 4.2.6 on 2023-10-28 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            'distance_checker',
            '0009_alter_corner_bolt_diameter_alter_corner_bolt_grade_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Ridge',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('case', models.CharField(max_length=50)),
                ('left_girder_angle', models.FloatField()),
                ('right_girder_angle', models.FloatField()),
                ('girder_height', models.IntegerField()),
                ('left_t_flange_girder', models.IntegerField()),
                ('right_t_flange_girder', models.IntegerField()),
                ('t_plate_connection', models.IntegerField()),
                (
                    'bolt_grade',
                    models.TextField(choices=[('8_8', '8.8'), ('10_9', '10.9')]),
                ),
                ('bolt_diameter', models.IntegerField()),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('distance_top', models.IntegerField(null=True)),
                ('distance_bottom', models.IntegerField(null=True)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
