# Generated by Django 4.2.6 on 2023-11-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars_calculation", "0003_calculationcfrhs_length_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationcfrhs",
            name="country",
            field=models.CharField(
                choices=[
                    ("Denmark", "Denmark"),
                    ("Germany", "Germany"),
                    ("Norway", "Norway"),
                    ("Sweden", "Sweden"),
                ],
                default=100,
            ),
            preserve_default=False,
        ),
    ]
