# Generated by Django 4.2.6 on 2023-10-22 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('distance_checker', '0004_corner_distance_bottom_corner_distance_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corner',
            old_name='name',
            new_name='case',
        ),
    ]
