# Generated by Django 4.2.6 on 2023-10-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('distance_checker', '0006_alter_corner_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corner',
            name='case',
            field=models.CharField(default='1000', max_length=50),
        ),
    ]
