# Generated by Django 4.2.6 on 2023-11-05 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileRhs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("H", models.IntegerField(help_text="Height of the object [mm]")),
                ("B", models.IntegerField(help_text="Width of the object [mm]")),
                ("T", models.FloatField(help_text="Thickness of the web [mm]")),
                ("G", models.FloatField(help_text="Nominal weight per [/m]")),
                ("surf", models.FloatField(help_text="Painting surface [/m]")),
                ("r0", models.FloatField(help_text="Radius r0 [mm]")),
                ("r1", models.FloatField(help_text="Radius r1 [mm]")),
                ("A", models.FloatField(help_text="Cross-section area [mm]")),
                (
                    "Iy",
                    models.FloatField(help_text="Moment of inertia about the Y [mm]"),
                ),
                (
                    "Iz",
                    models.FloatField(help_text="Moment of inertia about the Z [mm]"),
                ),
                ("Wply", models.FloatField(help_text="plastic_section Wply [mm]")),
                ("Wplz", models.FloatField(help_text="plastic_section Wplz [mm]")),
            ],
        ),
        migrations.CreateModel(
            name="CalculationCfrhs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case", models.CharField(max_length=50)),
                ("axial_force", models.FloatField()),
                ("bending_moment", models.FloatField()),
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("utilization_compression", models.IntegerField(null=True)),
                ("utilization_tension", models.IntegerField(null=True)),
                ("utilization_deformation", models.IntegerField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bars_calculation.profilerhs",
                    ),
                ),
            ],
        ),
    ]
