# Generated by Django 4.2.6 on 2023-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars_calculation", "0006_calculationcfrhs_eccentricity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculationcfrhs",
            name="utilization_compression",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="calculationcfrhs",
            name="utilization_deformation",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="calculationcfrhs",
            name="utilization_tension",
            field=models.FloatField(null=True),
        ),
    ]
