# Generated by Django 4.2.6 on 2023-11-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bars_calculation",
            "0007_alter_calculationcfrhs_utilization_compression_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailedCalculationCfrhs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_radius_gyration", models.FloatField()),
                ("buckling_curve", models.FloatField()),
                ("buckling_factor", models.FloatField()),
                ("epsilon", models.FloatField()),
                ("lambda_slenderness_1", models.FloatField()),
                ("buckling_length", models.FloatField()),
                ("lambda_relative_slenderness", models.FloatField()),
                ("theta_reduction_factor", models.FloatField()),
                ("chi_reduction_factor", models.FloatField()),
                ("tension_capacity", models.FloatField()),
                ("compression_capacity", models.FloatField()),
                ("total_bending", models.FloatField()),
                ("total_deflection", models.FloatField()),
                ("last_modified_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="calculationcfrhs",
            name="detailed",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="bars_calculation.detailedcalculationcfrhs",
            ),
            preserve_default=False,
        ),
    ]
