# Generated by Django 4.2.6 on 2023-11-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars_calculation", "0010_alter_detailedcalculationcfrhs_buckling_curve"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilerhs",
            name="Ix",
            field=models.FloatField(
                default=0, help_text="Torsional moment of inertia [mm^2]"
            ),
            preserve_default=False,
        ),
    ]
