# Generated by Django 4.2.6 on 2023-11-26 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bars_calculation", "0011_profilerhs_ix"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationRhs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case", models.CharField(max_length=50)),
                (
                    "type_profile",
                    models.CharField(
                        choices=[("Cold formed", "CF"), ("Hot formed", "HF")]
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Denmark", "Denmark"),
                            ("Germany", "Germany"),
                            ("Norway", "Norway"),
                            ("Sweden", "Sweden"),
                        ]
                    ),
                ),
                (
                    "steel",
                    models.CharField(
                        choices=[("S235", "S235"), ("S275", "S275"), ("S355", "S355")]
                    ),
                ),
                ("axial_force", models.FloatField()),
                ("eccentricity_y", models.FloatField()),
                ("eccentricity_z", models.FloatField()),
                ("bending_moment_y", models.FloatField()),
                ("bending_moment_z", models.FloatField()),
                ("shear_force_y", models.FloatField()),
                ("shear_force_z", models.FloatField()),
                ("length_profile", models.FloatField()),
                ("buckling_factor", models.FloatField()),
                ("limit_deformation", models.FloatField()),
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("utilization_shear", models.FloatField(null=True)),
                ("utilization_compression", models.FloatField(null=True)),
                ("utilization_tension", models.FloatField(null=True)),
                ("utilization_deformation", models.FloatField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetailedCalculationRhs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_radius_gyration_y", models.FloatField()),
                ("profile_radius_gyration_z", models.FloatField()),
                ("shear_capacity_y", models.FloatField()),
                ("shear_capacity_z", models.FloatField()),
                ("reduction_due_shear", models.FloatField()),
                ("tension_profile", models.FloatField()),
                ("check_tension_profile", models.FloatField()),
                ("bending_capacity_profile_y", models.FloatField()),
                ("bending_capacity_profile_z", models.FloatField()),
                ("reduced_bending_capacity_y", models.FloatField()),
                ("reduced_bending_capacity_z", models.FloatField()),
                ("reduction_biaxial_bending_capacity", models.FloatField()),
                ("check_interaction_axial_force_and_bending", models.FloatField()),
                ("buckling_curve", models.CharField()),
                ("epsilon", models.FloatField()),
                ("lambda_slenderness_1", models.FloatField()),
                ("buckling_length", models.FloatField()),
                ("lambda_relative_slenderness_y", models.FloatField()),
                ("lambda_relative_slenderness_z", models.FloatField()),
                ("theta_reduction_factor_y", models.FloatField()),
                ("theta_reduction_factor_z", models.FloatField()),
                ("chi_reduction_factor_y", models.FloatField()),
                ("chi_reduction_factor_z", models.FloatField()),
                ("compression_capacity_y", models.FloatField()),
                ("compression_capacity_z", models.FloatField()),
                ("check_buckling_y", models.FloatField()),
                ("check_buckling_z", models.FloatField()),
                ("check_total_buckling", models.FloatField()),
                ("total_bending_my", models.FloatField()),
                ("total_bending_mz", models.FloatField()),
                ("bending_capacity_y", models.FloatField()),
                ("bending_capacity_z", models.FloatField()),
                ("check_bending_y", models.FloatField()),
                ("check_bending_z", models.FloatField()),
                ("check_total_bending", models.FloatField()),
                ("Cmy", models.FloatField()),
                ("kyy", models.FloatField()),
                ("kzz", models.FloatField()),
                ("kzy", models.FloatField()),
                ("kyz", models.FloatField()),
                ("check_interaction_buckling_and_bending", models.FloatField()),
                ("check_deformation_y", models.FloatField()),
                ("check_deformation_z", models.FloatField()),
                ("check_deformation", models.FloatField()),
                ("last_modified_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="CalculationCfrhs",
        ),
        migrations.DeleteModel(
            name="DetailedCalculationCfrhs",
        ),
        migrations.AddField(
            model_name="calculationrhs",
            name="detailed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bars_calculation.detailedcalculationrhs",
            ),
        ),
        migrations.AddField(
            model_name="calculationrhs",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bars_calculation.profilerhs",
            ),
        ),
    ]
