# Generated by Django 4.2.6 on 2023-11-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars_calculation", "0012_calculationrhs_detailedcalculationrhs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculationrhs",
            name="type_profile",
            field=models.CharField(
                choices=[("CF", "Cold formed"), ("HF", "Hot formed")]
            ),
        ),
    ]
