# Generated by Django 4.2.6 on 2023-12-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars_calculation", "0013_alter_calculationrhs_type_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationrhs",
            name="cross_section_class",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="detailedcalculationrhs",
            name="profile_elastic_section_y",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detailedcalculationrhs",
            name="profile_elastic_section_z",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
