# Generated by Django 4.2.6 on 2023-12-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars_calculation", "0014_calculationrhs_cross_section_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedcalculationrhs",
            name="profile_shear_area_y",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detailedcalculationrhs",
            name="profile_shear_area_z",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
