# Generated by Django 4.2.6 on 2023-12-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bars_calculation",
            "0015_detailedcalculationrhs_profile_shear_area_y_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedcalculationrhs",
            name="section_class",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
